apiVersion: v1
kind: Service
metadata:
  name: {{ include "istio-routing-issue.fullname" . }}-a
  labels:
    {{- include "istio-routing-issue.labels" . | nindent 4 }}
    app.kubernetes.io/component: a
    version: 1.0.0
    app: a
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "istio-routing-issue.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: a
    version: 1.0.0
    app: a
